---
driver:
  name: docker

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos
    driver:
      image: centos:7.3.1611

suites:
  - name: default
    run_list:
      - recipe[boyrd::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
